version: '3'


volumes:
  pg_account_client:

services:
  app-2:
    restart: always
    container_name: app-2
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://postgres-2:5435/account_db'

  postgres:
    container_name: postgres-2
    image: postgres:16.1
    restart: always
    ports:
      - "5435:5436"
    environment:
      - POSTGRES_DB=account_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pg_account_client:/var/lib/postgresql/datant_db_client