create table new_account
(
    account_id       bigint generated by default as identity,
    uuid             varchar(255) not null,
    name             varchar(50)  not null,
    age              integer      not null,
    greeting_message varchar(255)
);